---
title: "Natural Connectivity"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(plyr)
require(ggplot2)


rm(list=ls(all=TRUE))
```

## R Markdown

 

```{r cars}
resultFolder <- "C:/Users/cxa123230/Dropbox/Publications/PostDoc work/Data Depth/results/"
figFolder <- "C:/Users/cxa123230/Dropbox/Publications/PostDoc work/Data Depth/ICDM/figs/"

names <- c("C3","Grid36","Ring34","Complete34","Karate")#,"Grid48","Grid100",

result<-data.frame()
 
  
for(name in names){ 
df <-(read.csv(paste(resultFolder,"topology",name,"Result.txt",sep=""),sep="\t",header=T))
df<-df[df$method=="degree",]
vec<- melt(rowSums(na.rm=TRUE,subset(df, select=5:length(df)))/length(df))
vec<-cbind(connectivity=vec,step=(1:nrow(vec)),network=name)
print(paste(name,nrow(vec)))
result<-rbind(result,vec) 

 
}
fig2<- ggplot(result,aes(x=step,y=(value), group = network,color=network))+scale_x_continuous(name="step")+geom_line(size=1.5)+geom_point(aes(shape=network), size=4)  +scale_shape_manual(values=c(0,4,2,1,3,5,6))+scale_y_sqrt(name=expression(mu[1]))+theme(legend.position = c(0.8, 0.6),text = element_text(size=16))
fig2  
 
ggsave(filename=paste(figFolder,"nConnecToy.pdf",sep=""),plot=fig2, width=6,height=4,unit="in")
```

 