---
title: "topology"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(plyr)
require(ggplot2)


rm(list=ls(all=TRUE))

resultFolder <- "C:/Users/cxa123230/Dropbox/Publications/PostDoc work/Data Depth/results/"
figFolder <- "C:/Users/cxa123230/Dropbox/Publications/PostDoc work/Data Depth/ICDM/figs/"

```

## R Markdown

 

```{r cars}
dfKarate <-(read.csv(paste(resultFolder,"topologyKarateresult.txt",sep=""),sep="\t",header=T))
dfKarate<-dfKarate[dfKarate$method!="depth",] 
fig1<- ggplot(dfKarate,aes(x=iteration,y=l2, group = method,color=method))+scale_x_continuous(breaks=c(0,4,8,12,16),name="step")+scale_y_continuous(name=expression(mu[1]))+geom_line(size=1.5)+geom_point(aes(shape=method), size=4)  +scale_shape_manual(values=c(0,4,2,1))+theme(legend.position = c(0.8, 0.6),text = element_text(size=20))
fig1  
ggsave(filename=paste(figFolder,"sRadiusKarate.pdf",sep=""),plot=fig1, width=6,height=4,unit="in")

dfKarate<-dfKarate[dfKarate$method=="degree",]
dfKarate<-cbind(dfKarate[,1:5],type="Karate") 

dfRing <-(read.csv(paste(resultFolder,"topologyRing34result.txt",sep=""),sep="\t",header=T))
dfRing<- cbind(dfRing[,1:5],type="Ring34")

df3 <-(read.csv(paste(resultFolder,"topologyC3result.txt",sep=""),sep="\t",header=T))

df3<- cbind(df3[,1:5],type="C3") 

dfGrid <-(read.csv(paste(resultFolder,"topologyGrid36result.txt",sep=""),sep="\t",header=T))
dfGrid<- cbind(dfGrid[,1:5],type="Grid36") 

dfComplete <-(read.csv(paste(resultFolder,"topologyComplete34Result.txt",sep=""),sep="\t",header=T))

dfComplete<- cbind(dfComplete[,1:5],type="Complete34") 

df<-rbind(dfRing,dfGrid,df3,dfKarate)

fig2<- ggplot(df,aes(x=iteration,y=(l1), group = type,color=type))+scale_x_continuous(breaks=c(0,4,8,12,16,20,24),name="step")+geom_line(size=1.5)+geom_point(aes(shape=type), size=4)  +scale_shape_manual(values=c(0,4,2,1))+scale_y_sqrt(name=expression(mu[1]))+theme(legend.position = c(0.8, 0.6),text = element_text(size=20))
fig2  
ggsave(filename=paste(figFolder,"sRadiusToy.pdf",sep=""),plot=fig2, width=6,height=4,unit="in")
 
```
```{r}
library(ggplot2)
real<-data.frame()
takeK=10
realWeb<-data.frame()
realCA<-data.frame()
realLoc<-data.frame()
realUn<-data.frame()
realDi <-data.frame()

realUn<-rbind(realUn,prep("Facebook",takeK,"Facebook"))
realUn<-rbind(realUn,prep("dblp",takeK,"Dblp"))
realUn<-rbind(realUn,prep("youtube",takeK,"Youtube"))
realUn<-rbind(realUn,prep("amazon",takeK,"Amazon"))

realDi<-rbind(realDi,prep("Epinions",takeK,"Epinions"))
realDi<-rbind(realDi,prep("wiki-vote",takeK,"wiki-vote"))
realDi<-rbind(realDi,prep("enron",takeK,"Enron"))

realLoc<-rbind(realLoc,prep("kite",takeK,"Brightkite"))
realLoc<-rbind(realLoc,prep("Gowalla",takeK,"Gowalla")) 

realCA<-rbind(realCA,prep("CA-GrQc",takeK,"CA-GrQc"))
realCA<-rbind(realCA,prep("CA-AstroPh",takeK,"CA-AstroPh"))
realCA<-rbind(realCA,prep("Ca-CondMat",takeK,"Ca-CondMat"))
realCA<-rbind(realCA,prep("CA-HepTh",takeK,"CA-HepTh"))


realWeb<-rbind(realWeb,prep("web-stanford",takeK,"Web-Stanford"))
realWeb<-rbind(realWeb,prep("web-notredame",takeK,"Web-Notredame"))
realWeb<-rbind(realWeb,prep("web-berkeley",takeK,"Web-Berkeley"))
realWeb<-rbind(realWeb,prep("web-google",takeK,"Web-Google"))



figWeb<- ggplot(realWeb,aes(x=(step),y=(radius), group = network,color=network))+scale_x_continuous(breaks=c(0,4,8,12,16,20,24),name="step")+geom_line(size=1.5)+geom_point(aes(shape=network), size=4)  +scale_y_continuous(name=expression(mu[1]))+theme(legend.position = c(0.8, 0.7),text = element_text(size=20))
figWeb 

ggsave(filename=paste(figFolder,"sRadiusWeb.pdf",sep=""),plot=figWeb, width=6,height=4,unit="in")

figCA<- ggplot(realCA,aes(x=(step),y=(radius), group = network,color=network))+scale_x_continuous(breaks=c(0,4,8,12,16,20,24),name="step")+geom_line(size=1.5)+geom_point(aes(shape=network), size=4)  +scale_y_continuous(name=expression(mu[1]))+theme(legend.position = c(0.8, 0.7),text = element_text(size=20))
figCA 
ggsave(filename=paste(figFolder,"sRadiusCa.pdf",sep=""),plot=figCA, width=6,height=4,unit="in")

figLoc<- ggplot(realLoc,aes(x=(step),y=(radius), group = network,color=network))+scale_x_continuous(breaks=c(0,4,8,12,16,20,24),name="step")+geom_line(size=1.5)+geom_point(aes(shape=network), size=4)  +scale_y_continuous(name=expression(mu[1]))+theme(legend.position = c(0.8, 0.7),text = element_text(size=20))
figLoc 
ggsave(filename=paste(figFolder,"sRadiusLoc.pdf",sep=""),plot=figLoc, width=6,height=4,unit="in")

figDi<- ggplot(realDi,aes(x=(step),y=(radius), group = network,color=network))+scale_x_continuous(breaks=c(0,4,8,12,16,20,24),name="step")+geom_line(size=1.5)+geom_point(aes(shape=network), size=4)  +scale_y_continuous(name=expression(mu[1]))+theme(legend.position = c(0.8, 0.7),text = element_text(size=20))
figDi 
ggsave(filename=paste(figFolder,"sRadiusDi.pdf",sep=""),plot=figDi, width=6,height=4,unit="in")

figUn<- ggplot(realUn,aes(x=(step),y=(radius), group = network,color=network))+scale_x_continuous(breaks=c(0,4,8,12,16,20,24),name="step")+geom_line(size=1.5)+geom_point(aes(shape=network), size=4)  +scale_y_continuous(name=expression(mu[1]))+theme(legend.position = c(0.8, 0.7),text = element_text(size=20))
figUn 
ggsave(filename=paste(figFolder,"sRadiusUn.pdf",sep=""),plot=figUn, width=6,height=4,unit="in")


prep<-function(dataset,takeK,name){
  df <-(read.csv(paste(resultFolder,dataset,"AdjacencyResult.txt",sep=""),sep="\t",header=T))
  df<-df[1:takeK,]
  radius<-df$l1/max(df$l1)
  rd<-cbind(df[,1:3],radius,network=name)
  return (rd)
}

```


















 